services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "4601:80"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - photo-network
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - minio
    volumes:
      - backend-uploads:/app/uploads
      - backend-temp:/app/temp
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - SERVER_URL=${SERVER_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    networks:
      - photo-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "4620:4620"
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT=false
      - HOST_URL=${HOST_URL}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":4620" --address ":${MINIO_PORT}"
    networks:
      - photo-network
    restart: unless-stopped
  minio-mc:
    image: minio/mc:latest
    ports:
      - "4621:4621"
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        mc alias set myminio http://minio:${MINIO_PORT} $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} &&
        mc mb myminio/${MINIO_BUCKET_NAME} --ignore-existing &&
        echo '✅ MinIO bucket created successfully';
      "
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
    networks:
      - photo-network
    restart: "no"

networks:
  photo-network:
    driver: bridge

volumes:
  backend-uploads:
  backend-temp:
  minio-data:
